# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_R=3.3.2
    - CONDA_R=3.4.1
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "g9DncoZIPm+SbPr3+4G+HhGiW8mjKNp5QvIjL6kSXiN6rfMnJqBN8Djs8JOWLq706Axsd80rmGC4bA8v/xaeUlFuQe+/KQhAWtpcbYsIhblz1eRMWdr7mTq7zcUSEvd13VvZr3w7XsYD/TRNtKxg83+yVmVKLW9zBVL+FP5Qmbt/lecliAIZgpwmt7my299kft/XBYL/OGVmBE1Te0nqsaVZ2+AdFKOEJBgJVkv5ml29GnEJtlBIekBGqf2UKNccyxUrdiCnxN9iXSFeGDuvqH1dBA/sepLe/9t6E3A4yyS1qqnWWBO64cgMT0WLAc99EyI9moXbWZtSaoRd5al9czPMqXzvOiIW2RMr0t4+WW169lUZlco9mIYk7+y6gKAtPgUiLEuRhSA8anxVsiwr96l4FeVik7wSn6iqovCnwV5EUslEZsQSyKrSDBK9QoJdrhzfMSRuf0s8PvpnJlG7xAaOoKmoJbwpY/vkRuAQKEAzHvEoeoaR6133ILQxCe8f0zTp56euPp+viu+9RraE18ghJXd4RJRuOQXCWKoMOISkRxHdaK1MoSmVd57tkUmREZISGTmWcWAeTTkYZxT7KtZMqnWyVBaHeO5s7SLAp7faKXr7AFl1ak1uaQSceBdEkjI54iOL92VGd6n13NDazcGt5FYEBh50sbrHLyoW9Vo="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
