travis:
  secure:
    BINSTAR_TOKEN: VmXlmsSXEc7STYbOMtjx52ufs4qDC6ugqFeMrqhLPZkMOKNIGnulkkO9goIbhJHYn5LNX7TS8o4J4eY7nkca9wkRAdKI/3ChizZ0nJ6IRRChysNjUyKlsActlKd5VdZ6Q3xGaOmoFVtqv0fRafSuUMAcMlYjcy/p0Gr0JJnjh4AtXkM/MaMszrCbi7NHTj9g7QhBUYKAubYjz0FkdudmCY8+vF7hzMM2pDTqPqaSXNcg1r1j0w+pG+INrgB5ivzlB7/nnJds7ipOME14NzWZ5+L2XpSY/X9JhF4i6IVCc+IgAHyEJarejz+j8mfdjFSgT15LhNEMQECMHH8zSjgz8tb2hd/9X8Gyd6zSs3cB8WJUp3RdUAgQ0jPuf9FHyBmUPxMYKpJexxcNhpRuQExOrFni8mYqCiwX71LFZ6BRrB/4+A02S8bZGiFnaaCwApEpHeAD8uwglsKR2awCIbqN52tzz2X9AXWVRFlJssXeR88GTPFSNroRbArxsc8SSchrkyQlgbRh2NzIHyTdrJYokErIn32xAVhJ0/QCb/eFPnn8AaZGDnXKUZT9uktPnxtP8mgJN/dKLRGYqLLGgHkIf60va9TURGMN+qEHgmj7sEkee8LSxf8QkcNsx/zp6uDrroLe5ywTRkCXoInVST0hL14+q0Ou9KiIQDSfC/odrCk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
