travis:
  secure:
    BINSTAR_TOKEN: Zco+y0YV+sn8R4Yw8BieBlagwOPAnub4JWIQDYRBD/Lqr+HJd/uPSS+i6vVHTMf5lZRUjhDVyIMKF5nxImAaCnnxKCZ2ODxtp/jwM/J5q4wpWqeuti9NhYnHCPN2TlyaRZfS6IhSCpUXgpNGkbN0vssJpHt1QuyMmRwwWSv4QfKL2JZbiEKtsjZ+8KxvuFTmACrfqq1Dk0P2HPxFQDKJjkm5gRC6xR9Mc89hyyjPXR+t24kKHf4bWLsKOWDH6FhXJyG/x44IXf+Shrtc1KSGAhUu49noGze6FO24ykzZ1++4Dsqs5U8fh0kJuAk5HMylWMhLBRMXzDNAwL2sfPLN4SUWbFFvoy87Lh2mHc0sWv0JiXXWniCPZDGHK8caZWJAaEMHbrClrczoVU7l5LN5Z9Pz8egepD4ikVlX7zbeIoP89krk0HBstXrCedNdXLre4zrgPajl7lmZIMqwwT8hLuQGuqpnSV1dFkBpZe/EYPLk5WfJjU4avwgA5YkCP5Fa5KHucBm/Ql7DljhYxyEW4XcVpl2BvRG5Zmc8n9DedBE5o/cjvsQ7PXlDBuIIyyfiDN3AVfLYaj8ECMch7uhvYKqJdFF7jsVwMaXOiIB0QEiUxdsoUfCqA9EBXLpff5inQSnRwC93bd7N104L6dew9OkKjpyKOvfr8QYn9CpJeVg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
