travis:
  secure:
    BINSTAR_TOKEN: g9DncoZIPm+SbPr3+4G+HhGiW8mjKNp5QvIjL6kSXiN6rfMnJqBN8Djs8JOWLq706Axsd80rmGC4bA8v/xaeUlFuQe+/KQhAWtpcbYsIhblz1eRMWdr7mTq7zcUSEvd13VvZr3w7XsYD/TRNtKxg83+yVmVKLW9zBVL+FP5Qmbt/lecliAIZgpwmt7my299kft/XBYL/OGVmBE1Te0nqsaVZ2+AdFKOEJBgJVkv5ml29GnEJtlBIekBGqf2UKNccyxUrdiCnxN9iXSFeGDuvqH1dBA/sepLe/9t6E3A4yyS1qqnWWBO64cgMT0WLAc99EyI9moXbWZtSaoRd5al9czPMqXzvOiIW2RMr0t4+WW169lUZlco9mIYk7+y6gKAtPgUiLEuRhSA8anxVsiwr96l4FeVik7wSn6iqovCnwV5EUslEZsQSyKrSDBK9QoJdrhzfMSRuf0s8PvpnJlG7xAaOoKmoJbwpY/vkRuAQKEAzHvEoeoaR6133ILQxCe8f0zTp56euPp+viu+9RraE18ghJXd4RJRuOQXCWKoMOISkRxHdaK1MoSmVd57tkUmREZISGTmWcWAeTTkYZxT7KtZMqnWyVBaHeO5s7SLAp7faKXr7AFl1ak1uaQSceBdEkjI54iOL92VGd6n13NDazcGt5FYEBh50sbrHLyoW9Vo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
