travis:
  secure:
    BINSTAR_TOKEN: kBUQNDTMvY7BTZ23Vlk8FepbMLMQOR37NMHc3Bj8Z3ADE0wDfv+1/KEOEt0S246cFyt8qzUPTEh7m9Q3cAeDBKMb2TKOY2W/1H9kIMy7K+RIfgXfhctwQwZoZLNFEJmMrjSOf8Fq8d7tpcGJeaGO9154Q6YF1F2QKIAzpZcwJm2WyWFn04lPTtOqLc5dQOV8WsJoB8UyaVAhx7EzUdY3PYHrgkjXGC+Em0IZxmVgc7PaYFAJCMLTCocuud7cO9NV0kpLWsPRZw7cA+OiYxiZIdbOCpnc4fMVzKB48zukpUcdvSfR4VeBOzSkip8lPH0Gf3+Npy4AUuDHPhngZpuVwhkaveQxuSW/UBO8kbaod/fwYcWGMX0zP7rU6/C/GTsQ+NUcoYTgxO3mYIAUKI6fWssKOu2No49zvjy1VI4P81lkCUGXTjelRfnVDN5FalV7ggW2uYUzCv5vZkyyp5kaTA5flu5kDn1uza+ZsScudMfgBdh2umuN9QtZN1no3liqmylh0ci7GO1xPxJ9RsPWyhu5u7FTCc9PsKBAIj+v1vxlNGsSNTnNXXDbificUkfeBHF7VJmSJbSLZBRkhbAJBpAv2/oqOdaTKmi6ME2HOqQBMs8FA4loI+l4vBmEa5MNnAsLNqV+jBmJmCVXa5i3F+b3jZQTC/1AzBqMPJThTww=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
