travis:
  secure:
    BINSTAR_TOKEN: VbYlWWXny6JQ/bRbUIZcmDemL8dCG2N3Ia+hjl/g4NCCkBBvxsfATr3ID5DqF8080zdTxdfV/a2MKf+mAPWoJxQVCPpJI1FhiGFz4yJmNyu4FkoZiT5FJlOQfBp3mTuOOgtcBsH7YqefLI10kdZHU3p61ODxuvHCgQlp11/6ZHRLCqoNORLXftwwgJJQfNgy55K9xEFOESThVkRvwLXhN9AWms0xeuSYHCDdue1lJQQQMR8loCHzDrUQI91sKoEQRi9VHezQxr1VJ/bjbUGgbBTf2ut062uNfa6cJqKplnhL3W2VpWjvxVc3fVPRx9sSLThmKuCbtCB4z9didKq9ycC8mSl8Nz3nEToKW4ZEul33K+rCqf4dF1V4U2TeQg4SRIv477Oy7ttta9GUAM6MvADNFQwPmR5zy2kN6lbL1kM7kuw8WIg5xINwRJl1JVS4KoqWXwax9K8TOtqIn9MiDD7knFEJOOQM2Lcw72SIZEuS//5BAzaeMaSUg992ontHjKA3iuyDtZ0nDi4NUqwcXuOuARjzunnhPpYyeQJBWtBs/xztEtbXYvuN7H4yMo7/aCoQlATnTpKWCpd8nVAJCyDZfNYj8tL8jOR4qVXUDrDQHl079oPm3hR8ys308Lx3SWCEgbTxTacg/XvBLSwa0VmmGAY/I6VQBGI/s2lhxfA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
